image:
  # -- image repository
  repository: thewolfnl/nakama
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # this example is not automatically updated, so be sure to use the latest image
  tag: latest

# -- Configures service settings for the chart.
service:
  main:
    ports:
      grpc:
        port: 7349
      http:
        port: 7350
      admin:
        port: 7351
      prometheus:
        port: 9100

# -- Override the command(s) for the default container
command: [ "/bin/sh" ]
# -- Override the args for the default container
args: 
  - "-ecx"
  - >
      /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
      exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: true
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: nakama.ritsma.nu
        paths:
          - path: /
    tls:
      - hosts:
          - nakama.ritsma.nu
        secretName: tls-nakama
  admin:
    enabled: true
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: admin.nakama.ritsma.nu
        paths:
          - path: /
    tls:
      - hosts:
          - admin.nakama.ritsma.nu
        secretName: tls-nakama-admin

# -- Configure persistence settings for the chart under this key.
persistence:
  data:
    enabled: false
    mountPath: /nakama/data
    type: hostPath
    hostPath: /application/nakama/