#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    type: NodePort
    ports:
      http:
        enabled: false
      gametcp:
        enabled: true
        primary: true
        port: 7777
        protocol: TCP
      game:
        enabled: true
        port: 7777
        protocol: UDP

# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.0.3/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
controllers:
  main:
    strategy: RollingUpdate
    containers:
      main:
        image:
          # -- image repository
          repository: wolveix/satisfactory-server
          # @default -- chart.appVersion
          tag: latest
          # -- image pull policy
          pullPolicy: Always
        env:
          TZ: UTC # -- Set the container timezone
          AUTOPAUSE: true # -- pause game when no player is connected
          # AUTOSAVEINTERVAL: 300 # -- autosave interval in seconds
          # AUTOSAVENUM: 5 # -- number of rotating autosave files
          # AUTOSAVEONDISCONNECT: true # -- autosave when last player disconnects
          # CRASHREPORT: true # -- automatic crash reporting
          # DEBUG: false # -- for debugging the server
          # DISABLESEASONALEVENTS: false # -- disable the FICSMAS event (you miserable bastard)
          # MAXPLAYERS: 4 # -- set the player limit for your server
          # PGID: 1000 # -- set the group ID of the user the server will run as
          # PUID: 1000 # -- set the user ID of the user the server will run as
          ROOTLESS: false # -- allow the server to run as root
          # SERVERIP: 0.0.0.0    # -- set the game's ip
          # SKIPUPDATE: false # -- avoid updating the game on container start/restart
          STEAMBETA: false # -- set experimental game version
        resources: {}
        #   limits:
        #     # cpu: 100m
        #     memory: 6Gi
        #   requests:
        #     # cpu: 100m
        #     memory: 4Gi

        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - /healthcheck.sh
          startup:
            enabled: true
            type: TCP

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /application/satisfactory
    hostPathType: DirectoryOrCreate
