#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: wolveix/satisfactory-server
  # @default -- chart.appVersion
  tag: latest
  # -- image pull policy
  pullPolicy: always

# -- environment variables. See [plex docs](https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/) for more details.
# **NOTE:** Plex preference options are camelCase and CASE SENSITIVE!
# You can do horrible things to your Plex configuration if you are not careful
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  AUTOPAUSE: true # -- pause game when no player is connected
  # AUTOSAVEINTERVAL: 300 # -- autosave interval in seconds
  # AUTOSAVENUM: 5 # -- number of rotating autosave files
  # AUTOSAVEONDISCONNECT: true # -- autosave when last player disconnects
  # CRASHREPORT: true # -- automatic crash reporting
  # DEBUG: false # -- for debugging the server
  # DISABLESEASONALEVENTS: false # -- disable the FICSMAS event (you miserable bastard)
  # MAXPLAYERS: 4 # -- set the player limit for your server
  # PGID: 1000 # -- set the group ID of the user the server will run as
  # PUID: 1000 # -- set the user ID of the user the server will run as
  ROOTLESS: false # -- allow the server to run as root
  # SERVERIP: 0.0.0.0    # -- set the game's ip
  # SKIPUPDATE: false # -- avoid updating the game on container start/restart
  STEAMBETA: false # -- set experimental game version

resources:
  limits:
    # cpu: 100m
    memory: 6Gi
  requests:
    # cpu: 100m
    memory: 4Gi

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    type: NodePort
    ports:
      http:
        enabled: false
        primary: false
      game:
        enabled: true
        port: 7777
        protocol: UDP
      game2:
        enabled: true
        port: 7777
        protocol: TCP

# make nodeports work
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /application/satisfactory

  # server download game files from steam to the below folder
  # recommend this is kept in a seperate PVC so just config can be backed up.
  # no point backing up downloaded game content
  server-cache:
    enabled: false
    mountPath: /config/gamefiles
    accessMode: ReadWriteOnce
    size: 20Gi

# Probes are not currently used
# as it is difficult to detect liveness of a UDP server
probes:
  startup:
    enabled: false

  liveness:
    enabled: false

  readiness:
    enabled: false
