#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: pihole/pihole
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam
  # -- Set a secure password here or it will be random
  # WEBPASSWORD: ''

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80
  dns:
    type: NodePort
    enabled: true
    ports:
      dns-tcp:
        enabled: true
        port: 53
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
  dhcp:
    # Only required if you are using Pi-hole as your DHCP server
    enabled: false
    ports:
      dhcp:
        enabled: true
        port: 67
        protocol: UDP

# make nodeports work
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: pi.ritsma.nu
        paths:
          - path: /
    tls:
      - hosts:
          - pi.ritsma.nu
        secretName: tls-pi

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /etc/pihole
    type: hostPath
    hostPath: /application/pihole/
  dnsmasq:
    enabled: true
    mountPath: /etc/dnsmasq.d
    type: hostPath
    hostPath: /application/dnsmasq.d/

# -- Security contexts required for container.
# @default -- see values.yaml
securityContext:
  capabilities:
    add:
      # Only required if you are using Pi-hole as your DHCP server
      # - NET_ADMIN
