#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: zwavejs/zwave-js-ui
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://zwave-js.github.io/zwavejs2mqtt/#/guide/env-vars) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam
  # -- Zwave Network key
  NETWORK_KEY:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8091
      websocket:
        enabled: true
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: zwave.ritsma.nu
        paths:
          - path: /
    tls:
      - hosts:
          - zwave.ritsma.nu
        secretName: tls-zwave

securityContext:
  # -- (bool) Privileged securityContext may be required if USB devices are accessed directly through the host machine
  privileged: true

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /usr/src/app/store
    type: hostPath
    hostPath: /application/zwavejs/
  # -- Configure a hostPathMount to mount a USB device in the container.
  # @default -- See values.yaml
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-0658_0200-if00
    mountPath: /dev/zwave

# -- Affinity constraint rules to place the Pod on a specific node.
# [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
affinity: {}
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zwave-controller