image:
  # -- image repository
  repository: cockroachdb/cockroach
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # this example is not automatically updated, so be sure to use the latest image
  tag: latest-v22.1

# -- Configures service settings for the chart.
service:
  main:
    ports:
      admin:
        port: 8080
      main:
        port: 26257

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
persistence:
  data:
    enabled: true
    mountPath: /cockroach-data
    type: hostPath
    hostPath: /datapool/dockerdata/cockroachdb/