#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: flobz/psa_car_controller
  # -- image tag
  tag: v3.0.12
  # -- image pull policy
  pullPolicy: IfNotPresent

# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    class: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: psa-car.ritsma.nu
        paths:
          - path: /
    tls:
      - hosts:
          - psa-car.ritsma.nu
        secretName: tls-psa-car

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    type: hostPath
    hostPath: /application/psa-car-controller/
