---
apiVersion: v2
appVersion: 2023.2.5
description: Home Assistant
name: home-assistant
version: 13.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/thewolfnl/helm-charts/tree/master/charts/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/home-assistant/home-assistant
  - https://hub.docker.com/r/homeassistant/home-assistant
  - https://github.com/thewolfnl/helm-charts/tree/master/charts/home-assistant
maintainers:
  - name: Tjeerd Ritsma
    email: tpritsma@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.2
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.3.5
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.3.2