---
apiVersion: v2
appVersion: v4.4.2
description: qBittorrent is a cross-platform free and open-source BitTorrent client
name: qbittorrent
version: 1.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - qbittorrent
  - torrrent
home: https://github.com/thewolfnl/helm-charts/tree/master/charts/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/k8s-at-home/container-images
  - https://github.com/thewolfnl/helm-charts/tree/master/charts/qbittorrent
maintainers:
  - name: Tjeerd Ritsma
    email: tpritsma@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: update vpn volume mount for loading config
    - kind: changed
      description: update vpn addon config
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.3.2